import Head from "next/head";
import { Inter } from "@next/font/google";
import { Sidebar } from "../components/Sidebar";
import { Feeds } from "../components/Feeds";
import { Widgets } from "../components/Widgets";

const inter = Inter({ subsets: ["latin"] });

export default function Home({ newsResults, randomUsers }) {
  return (
    <>
      <Head>
        <title>Tweeta</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen  mx-auto">
        <Sidebar />
        <Feeds />
        <Widgets
          newsResults={newsResults.articles}
          randomUsers={randomUsers.results}
        />
      </main>
    </>
  );
}

("https://saurav.tech/NewsAPI/top-headlines/category/sports/us.json");

export const getServerSideProps = async () => {
  const newsResults = await fetch(
    "https://saurav.tech/NewsAPI/top-headlines/category/technology/us.json"
  ).then((result) => result.json());

  const randomUsers = await fetch("https://randomuser.me/api/?results=10").then(
    (user) => user.json()
  );

  return {
    props: { newsResults, randomUsers },
  };
};
